#### Selinux

  - name: configure selinux
    selinux:  state={{ selinux_state }} policy={{ selinux_policy }}
    register: selinuxchange

  - name: restart machine in one minute if selinux was changed
    command: shutdown -r +1 now "Ansible updates triggered. Rebooting in under 1min"
    async: 0
    poll: 0
    ignore_errors: true
    when: selinuxchange.changed
    register: restartselinux

  - name: if restart, wait min 90s(+300s) for server to come back after reboot
    local_action: wait_for host={{ inventory_hostname }}
                  port=22
                  state=started
                  delay=90
                  timeout=300
    sudo: false
    when: restartselinux.changed

